### ISSUE TITLE
Thiết kế Class Diagram

### ISSUE THREAD

**Issue by quynhbud** [quynhbud/Kid-Monitoring-Application#10]

**Comment by Tungocyenvy** [comment]
Link lược đồ:https://drive.google.com/drive/folders/1ju-y43xEbW5qDvq3lQ8KM_OoLngeeTH-?usp=sharing
![image](https://user-images.githubusercontent.com/74482521/112859518-1df99480-90dd-11eb-92dc-9357a03c13dd.png)

**Comment by quynhbud** [comment]
[Nhom08_ClassDiagram.pdf](https://github.com/quynhbud/Kid-Monitoring-Application/files/6639563/Nhom08_ClassDiagram.pdf)

**Comment by quynhbud** [comment]
https://drive.google.com/file/d/17RZQ_cDp94niWWZuntYMULzxPw5iZ33S/view?usp=sharing
