### ISSUE TITLE
Yêu cầu chức năng

### ISSUE THREAD

**Issue by quynhbud** [quynhbud/Kid-Monitoring-Application#3]
bao gồm: yêu cầu user và yêu cầu hệ thống

**Comment by CuocThien** [comment]
**1. Đăng nhập/Đăng xuất**
1.1 Tạo tài khoản cho phụ huynh
1.2 Kết nối 2 thiết bị bằng tài khoản vừa đăng ký
1.3 Cho phép các quyền truy cập vào thiết bị của trẻ


**2. Quản lý thời gian sử dụng thiết bị**
2.1  Ứng dụng theo dõi thời gian sử dụng thiết bị hàng ngày
2.2 Đặt và quản lý giới hạn thời gian sử dụng ứng dụng cụ thể hàng ngày

**3.  Chặn trang web & Chặn video YouTube**
3.1 Theo dõi các trang web mà trẻ đã truy cập
3.2 Bộ lọc web cho phép bạn bảo vệ trẻ khỏi các trang web và nội dung độc hại
3.3 Theo dõi các video YouTube mà trẻ đã xem
3.4 Chặn các kênh và video trên YouTube
3.5 Bật chức năng Tìm kiếm an toàn để bảo vệ các lượt tìm kiếm trực tuyến của trẻ

**4. Khóa ứng dụng & Khóa điện thoại:**
4.1 Chặn ứng dụng và chặn trò chơi
4.2 Chặn ứng dụng mạng xã hội
4.3 Giới hạn thời gian sử dụng ứng dụng và giới hạn thời gian sử dụng từ xa

**Comment by NamTranQuoc** [comment]
Các chức năng sau khi chỉnh sửa lại

1. đăng nhập/ đăng ký

2. thiết bị quản lý và bật tắt chế độ quản lý (cần đăng nhập)
2.1 thiết bị quản lý (có thể quản lý nhiều thiết bị)
- quản lý thiết bị từ xa (Quản lý một đt khác)
- quản lý trên thiết bị hiện tại (quản lý đt thoại này)
2.2 bật tắt chế độ quản lý trên từng thiết bị

3. quản lý chung
3.1 quản lý về thời gian sử dụng thiết bị
3.2 lưu lại lịch sử sử dụng thiết bị
3.3 khóa điện thoại

4. quản lý ứng dụng
4.1 quản lý thời gian sử dụng ứng dụng
4.2 gỡ cài đặt và thêm ứng dụng vào các ứng dụng cấm
4.3 theo dõi thời gian sử dụng ứng dụng

5. quản lý truy cập web
5.1 bộ lọc web (có thể tự thêm vào danh sách web bị chặn hoặc dùng các mẫu có sẳn)
5.2 tìm kiếm an toàn (lọc các kết quả tìm kiếm phù hợp để hiển thị)
5.3 theo dõi các trang web đã truy cập
