### ISSUE TITLE
Test case 

### ISSUE THREAD

**Issue by quynhbud** [quynhbud/Kid-Monitoring-Application#45]

**Comment by Tungocyenvy** [comment]
[Nhom10_TestCaseLogin.xlsx](https://github.com/quynhbud/Kid-Monitoring-Application/files/6447471/Nhom10_TestCaseLogin.xlsx)
[Nhom10_TestCaseRegister.xlsx](https://github.com/quynhbud/Kid-Monitoring-Application/files/6447472/Nhom10_TestCaseRegister.xlsx)
