### ISSUE TITLE
Đặc tả yêu cầu bằng use case

### ISSUE THREAD

**Issue by quynhbud** [quynhbud/Kid-Monitoring-Application#7]

**Comment by CuocThien** [comment]
Đặc tả yêu cầu bằng usecase:
[https://drive.google.com/file/d/1xabw_LzhWowIUtnKSaiPL0iI5HVNRTMl/view?usp=sharing](url)

**Comment by CuocThien** [comment]
https://drive.google.com/file/d/1xabw_LzhWowIUtnKSaiPL0iI5HVNRTMl/view?usp=sharing

**Comment by CuocThien** [comment]
Đặc tả yêu cầu bằng usecase:
https://drive.google.com/file/d/1xabw_LzhWowIUtnKSaiPL0iI5HVNRTMl/view?usp=sharing

**Comment by Tungocyenvy** [comment]
![image](https://user-images.githubusercontent.com/74482521/112262804-d029fa00-8ca0-11eb-9971-565d2c8c4615.png)

**Comment by NamTranQuoc** [comment]
cập nhập lại usecase
link: https://drive.google.com/file/d/1B8KyfFjGPqIIAP6N-px93u1MokZHU4Oi/view?usp=sharing
