### ISSUE TITLE
Thiết kế Sequence Diagram

### ISSUE THREAD

**Issue by quynhbud** [quynhbud/Kid-Monitoring-Application#9]

**Comment by Tungocyenvy** [comment]
Link lược đồ:https://drive.google.com/drive/folders/1ju-y43xEbW5qDvq3lQ8KM_OoLngeeTH-?usp=sharing
![image](https://user-images.githubusercontent.com/74482521/112859518-1df99480-90dd-11eb-92dc-9357a03c13dd.png)

**Comment by CuocThien** [comment]
Link các lược đồ tuần tự:
https://drive.google.com/drive/folders/1JV7-4Mp2hswBuAD6AHBNWIYqcgmxndQt?usp=sharing

**Comment by quynhbud** [comment]
[Nhom08_SequenceDiagram.pdf](https://github.com/quynhbud/Kid-Monitoring-Application/files/6639542/Nhom08_SequenceDiagram.pdf)

**Comment by quynhbud** [comment]
https://drive.google.com/file/d/1JE515bo0NoBFllOlwwPBmbSQQJDDw6-S/view?usp=sharing
